### ISSUE TITLE
get_updates timeout option doesn't appear to be working

### ISSUE THREAD

**Issue by col** [zhyu/nadia#2]
I was expecting this command to not timeout for 120 seconds. 
```Nadia.get_updates([timeout: 120])```

Unfortunately no matter what I set it to I get the following error after about 8 seconds.
```{:error, %Nadia.Model.Error{reason: :timeout}}```

**Comment by mendab1e** [comment]
I think that the timeout option is working, but telegram servers return the timeout error ```{:error, %Nadia.Model.Error{reason: :timeout}}``` if a timeout value is to big. For example, when I set timeout value to 4 seconds, it returns the result after 4 seconds of polling. 
Btw, you can match this error to call get_updates method again.

**Comment by zhyu** [comment]
Hi, @col 
Thanks for pointing it out.
This issue relates to HTTPoison. The default timeout of HTTPoison is 8 seconds.
https://github.com/edgurgel/httpoison/blob/87aabe18be27bf25af2a4182b4754cd0a35aa1dd/lib/httpoison/base.ex#L126-L138
I'll fix this later.
For now, you can match this error as @mendab1e said.

**Comment by mendab1e** [comment]
@zhyu I've fixed it, but the problem was in default value of recv_timeout option which is set to 5 seconds. So that timeout greater than 4 seconds wasn't working for me.

**Comment by zhyu** [comment]
@mendab1e you're right, it was related to `recv_timeout`. #6 has been merged. Thank you!

**Comment by holyxiaoxin** [comment]
I'm currently using v0.3.3. Any timeout params more than 4 is still throwing a `{:error, %Nadia.Model.Error{reason: :timeout}}` error.

**Comment by zhyu** [comment]
@holyxiaoxin you can use github version, or waiting for the next release.

**Comment by holyxiaoxin** [comment]
`{:nadia, git: "https://github.com/zhyu/nadia"}`, which file should i point to?

**Comment by holyxiaoxin** [comment]
It's working. Thanks. (:

**Comment by holyxiaoxin** [comment]
For faster networks, it seems ok. But i get timeout often for slowly networks (higher latency). Would you like to add 5seconds instead of 1seconds instead? : `+    timeout = ((options[:timeout] || @default_timeout) + 1) * 1000`

**Comment by zhyu** [comment]
@holyxiaoxin You can just use a new timeout value which is 4 seconds greater than the old value you used.

from this:
```elixir
timeout = 10
Nadia.get_me([timeout: timeout])
```

to this:
```elixir
timeout = 10 + 4
Nadia.get_me([timeout: timeout])
```

**Comment by holyxiaoxin** [comment]
I think you've mistaken my concern. 

recv_timeout that is set by `timeout = ((options[:timeout] || @default_timeout) + 1) * 1000` in [here](https://github.com/zhyu/nadia/commit/e355a741ea695ca320802623ed831070cc6e2c7f), should be `timeout = ((options[:timeout] || @default_timeout) + 5) * 1000` instead. This is to accommodate the latency for wireless connection. 

recv_timeout >= latency from user to host(wired: <1ms, wireless 100-1000ms), local/oceanic RTT for request time (5-500ms), timeout option.

**Comment by mendab1e** [comment]
As far as I get, @holyxiaoxin means that currently `recv_timeout` is equal to telegram timeout + 1s. So he can't get response from telegram server after telegram timeout in 1 second because of recv_timeout. And even if he passes timeout value + 4, `recv_timeout` anyway will be timeout + 1s

**Comment by holyxiaoxin** [comment]
Yes, that's because the latency from my wireless connection + request RTT is more than 1s.

Thanks @mendab1e for clarifying.

**Comment by zhyu** [comment]
@holyxiaoxin, sorry for my misunderstanding.
@mendab1e, thanks!

Maybe changing the value from 1 to 5 can solve this issue, but I'm not sure what is the best value for it.
Anyway, pull requests are always welcome!

**Comment by zhyu** [comment]
maybe we should have a configurable `recv_timeout`?

**Comment by mendab1e** [comment]
I think that it is a good idea to add optional `recv_timeout` argument, because 5 seconds may be not enough for someone.

**Comment by holyxiaoxin** [comment]
i think it's good enough for 8s. that's the default for httppoison. i've sent a pr. please have a look.

**Comment by zhyu** [comment]
I'd like to have a `recv_timeout` in `config.exs`, since I don't prefer to add argument which telegram bot api does not have.

**Comment by holyxiaoxin** [comment]
I will update my pr to include config tech_timeout.
